name: "Lint, Build & Test"

on:
  workflow_call:
    inputs:
      package_name:
        description: "The pnpm package name."
        required: true
        type: string
      with_network:
        default: false
        description: "Whether a local avm network is used to run tests alongside."
        required: false
        type: boolean

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ› Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "ğŸ”§ Setup"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "ğŸ‘• Lint"
        run: pnpm -F ${{ inputs.package_name }} run lint

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ› Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "ğŸ”§ Setup"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "ğŸ—ï¸ Build"
        run: |
          pnpm -F ${{ inputs.package_name }} run build:dependencies
          pnpm -F ${{ inputs.package_name }} run build

  test:
    if: ${{ inputs.with_network == false }}
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ› Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "ğŸ”§ Setup"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "ğŸ§ª Test"
        run: |
          pnpm -F ${{ inputs.package_name }} run build:dependencies
          pnpm -F ${{ inputs.package_name }} run test

  test_with_network:
    if: ${{ inputs.with_network == true }}
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ› Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "ğŸ”§ Setup"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "ğŸ§ª Test"
        run: |
          ./scripts/test_with_network.sh "${{ inputs.package_name }}"
